dist: xenial
language: python
sudo: false
services :
 - docker
 - mysql
 - postgresql
python:
 - 3.6
 - 3.7

addons:
  apt:
    packages:
    - slapd
    - ldap-utils

env:
 - DATABASE_URL=postgres://postgres@/karaage
 - DATABASE_URL=mysql://root:@localhost/karaage
 - DATABASE_URL=sqlite://

install:
# Install database drivers
  - bash -c "if [[ $DATABASE_URL = postgres* ]]; then pip install psycopg2==2.7.3.1; fi; "
  - bash -c "if [[ $DATABASE_URL = mysql* ]]; then pip install mysqlclient==1.3.12; fi; "
# Install other dependancies
  - pip install -rrequirements/tests.txt

before_script:
  - bash -c "if [[ $DATABASE_URL = postgres* ]]; then psql -c 'create database karaage;' -U postgres; fi; "
  - bash -c "if [[ $DATABASE_URL = mysql* ]]; then mysql -e 'CREATE DATABASE IF NOT EXISTS karaage;'; fi; "

script:
  - python -m tldap.test.slapd ./run_tests.sh

jobs:
  include:
    - stage: beta
      if: branch = master and type = push
      install:
      script:
      - docker build
            --file "Dockerfile"
            --tag "brianmay/karaage:slurm17.02-beta"
            --build-arg "SLURM_VER=17.02"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker build
            --file "Dockerfile.apache"
            --tag "brianmay/karaage:slurm17.02-apache-beta"
            --build-arg "SLURM_VER=17.02"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push "brianmay/karaage:slurm17.02-beta"
      - docker push "brianmay/karaage:slurm17.02-apache-beta"
    - stage: deploy
      if: type = push and tag =~ ^v
      install:
      script:
      - docker build
            --file "Dockerfile"
            --tag "brianmay/karaage:slurm17.02"
            --build-arg "SLURM_VER=17.02"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker build
            --file "Dockerfile.apache"
            --tag "brianmay/karaage:slurm17.02-apache"
            --build-arg "SLURM_VER=17.02"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push "brianmay/karaage:slurm17.02"
      - docker push "brianmay/karaage:slurm17.02-apache"
      deploy:
        provider: pypi
        user: "penguin_brian"
        password:
          secure: BQaJb9cNx4fX5j/eLPjyvBq20N9gd3QWtq42qgBjF68608qIWKo3BtrNG87JtN1MkdZJDDUPdTjeQnwnjYfxbZvzaiJ32i+JyO92HlBL51DdSpppMVlalO0yYDos4ZHPi61M1xOu1DGPIl6vUaYamHI8ylpf8mWeO/UBp3uuq2M=
        distributions: "sdist bdist_wheel"
        on:
          all_branches: true
